### PR TITLE
fix(search): filters for docs and LO search

### LINKED ISSUE #118: Search function not working when filter set to all fields
grafik
grafik
grafik
grafik

### PR DESCRIPTION
**Pull request by FoxtrotSierra6829**
fixes #118 (again) for docs search and LO search
LO search previously didn't take field filters into account at all

### CODE REVIEW

File: libs/core/app/src/search/learning-objective-search.ts [hunk 1]
```diff
@@ -125,6 +125,11 @@ export const searchLearningObjectives = async ({
 }) => {
   const opts: SearchOptions = {
     fuzzy: 0.2,
+    fields: ps.searchField
+      ? ps.searchField === "all"
+        ? undefined
+        : [ps.searchField]
+      : undefined,
```
Comment (PupoSDC) [inline libs/core/app/src/search/learning-objective-search.ts:132]: `ps.searchField` can never be undefined; Zod makes sure of that. So this can simply be: 

```ts
    fields: ps.searchField === "all" ? undefined : [ps.searchField],
```

The reason why the field search here was a placebo is because the tokenizer breaks apart the learning objectives on "dots" making the search via ID completely useless (010.10, will return any LO that contains `010` and `01`.

On my WIP I was able to improve this by doing:

```ts
const SEARCH_INDEX = new MiniSearch<SearchDocument>({
  fields: [/** **/],
  storeFields: ["id"] satisfies SearchField[],
  tokenize: (s, fieldName) => {
    if (fieldName === "learningObjectives") return s.split(", ");
    return MiniSearch.getDefault("tokenize")(s, fieldName);
  },
});
``` 

and then for the `opts`

```ts
  const opts: SearchOptions = {
    fuzzy: idSearchFields.includes(ps.searchField) ? false : 0.2,
    prefix: idSearchFields.includes(ps.searchField),
    fields: ps.searchField === "all" ? undefined : [ps.searchField],
    tokenize: (s) => {
      if (ps.searchField === "learningObjectives") return s.split(", ");
      return MiniSearch.getDefault("tokenize")(s);
    },
  };
```

Long story short, the goal is to use Fuzzy search for text fields, and prefix  search(ie.: exact matches) for ID fields. it's also vital that for learningObjectives, and IDS the tokenizer does not split on "."

This is mostly non actionable right now, just sharing in case you are interested in improving the search a bit more in the future :D

**Review by PupoSDC — APPROVED** [review]
LGTM 🍔 

would be nice to remove the redundant null/check, but I will merge this one way or the other in the morning.

File: libs/core/app/src/search/learning-objective-search.ts (hunk 1 above)
Comment (FoxtrotSierra6829) [reply libs/core/app/src/search/learning-objective-search.ts:132]: Oh alright, I was wondering why for some terms the LO search gives good results and sometimes they're barely related. Makes sense

**Review by PupoSDC — APPROVED** [review]
